name: Develop Pull Request (CI)

on:
  pull_request:
    branches: [develop]

env:
  NODE_VERSION: '12'

jobs:
  deploy:
    name: ğŸš§ Lint, Test & Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Node.js dependencies
        run: |
          cd factory/simulators
          npm install

      - name: ğŸ•µï¸â€â™‚ï¸  Lint
        run: |
          cd factory/simulators
          npm run-script lint --if-present

      - name: ğŸ§ª  Test
        run: |
          cd factory/simulators
          npm run test --if-present

      - name: ğŸš§  Build
        run: |
          cd factory/simulators
          npm run build
